# Generated by Django 3.2.4 on 2021-10-30 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRecordsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners_name', models.CharField(max_length=100)),
                ('property_value_current_year', models.CharField(max_length=100)),
                ('property_value_next_year', models.CharField(max_length=100)),
                ('tax_value', models.CharField(max_length=100)),
                ('record_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider1.scraperecordsinventory')),
            ],
        ),
    ]
