# Generated by Django 3.2.4 on 2021-10-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperecords',
            name='billing_address',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='scraperecords',
            name='block',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='scraperecords',
            name='borough',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='scraperecords',
            name='link',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='scraperecords',
            name='lot',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
