# Generated by Django 3.2.4 on 2021-10-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spider1', '0002_auto_20211030_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndoneNotices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borough', models.CharField(default='None', max_length=100)),
                ('block', models.CharField(default='None', max_length=100)),
                ('lot', models.CharField(default='None', max_length=100)),
                ('exception_type', models.CharField(default='None', max_length=200)),
                ('time_exception', models.CharField(default='None', max_length=150)),
                ('scrape_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider1.scraperecords')),
            ],
        ),
    ]
