# Generated by Django 3.2.4 on 2021-11-01 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spider1', '0004_auto_20211101_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperecordsinventory',
            name='time_rec',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 1, 6, 52, 52, 804977, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='undonenotices',
            name='time_exception',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 1, 6, 52, 52, 806017, tzinfo=utc)),
        ),
    ]
