# Generated by Django 3.2.4 on 2021-11-01 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spider1', '0005_auto_20211101_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperecordsinventory',
            name='time_rec',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='undonenotices',
            name='time_exception',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
